# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "openamplify/version"

Gem::Specification.new do |s|
  s.name        = "openamplify"
  s.version     = OpenAmplify::VERSION
  s.authors     = ["Greg Moreno"]
  s.email       = ["greg.moreno@gmail.com"]
  s.homepage    = ""
  s.summary     = "Wrapper for the OpenAmplify API"
  s.description = "The OpenAmplify API reads text you supply and returns linguistic data explaining and classifying the content."

  s.rubyforge_project = "openamplify"

  s.files         = `git ls-files`.split("\n")

  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]

  s.add_dependency 'faraday'
  s.add_development_dependency 'minitest'
  s.add_development_dependency 'nokogiri'
end



## Generated by jeweler
## DO NOT EDIT THIS FILE DIRECTLY
## Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
## -*- encoding: utf-8 -*-
#
#Gem::Specification.new do |s|
#  s.name = %q{openamplify}
#  s.version = "0.2.3"
#
#  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
#  s.authors = ["Greg Moreno"]
#  s.date = %q{2010-06-22}
#  s.description = %q{The OpenAmplify API reads text you supply and returns linguistic data explaining and classifying the content.}
#  s.email = %q{greg.moreno@gmail.com}
#  s.extra_rdoc_files = [
#    "LICENSE",
#     "README.rdoc"
#  ]
#  s.files = [
#    ".gitignore",
#     "History",
#     "LICENSE",
#     "README.rdoc",
#     "Rakefile",
#     "VERSION.yml",
#     "lib/openamplify.rb",
#     "lib/openamplify/validations.rb",
#     "openamplify.gemspec",
#     "test/test_openamplify.rb"
#  ]
#  s.homepage = %q{http://github.com/gregmoreno/openamplify}
#  s.rdoc_options = ["--charset=UTF-8"]
#  s.require_paths = ["lib"]
#  s.rubygems_version = %q{1.3.6}
#  s.summary = %q{Wrapper for the OpenAmplify API}
#  s.test_files = [
#    "test/test_openamplify.rb"
#  ]
#
#  if s.respond_to? :specification_version then
#    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
#    s.specification_version = 3
#
#    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
#      s.add_runtime_dependency(%q<json>, ["~> 1.2"])
#      s.add_development_dependency(%q<shoulda>, ["~> 2.11"])
#    else
#      s.add_dependency(%q<json>, ["~> 1.2"])
#      s.add_dependency(%q<shoulda>, ["~> 2.11"])
#    end
#  else
#    s.add_dependency(%q<json>, ["~> 1.2"])
#    s.add_dependency(%q<shoulda>, ["~> 2.11"])
#  end
#
#  s.add_dependency 'multi_json'
#  s.add_development_dependency 'minitest'
#end

