# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{openamplify}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Moreno"]
  s.date = %q{2010-06-05}
  s.description = %q{The OpenAmplify API reads text you supply and returns linguistic data explaining and classifying the content.}
  s.email = %q{rubyoncloud@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "lib/openamplify.rb",
     "openamplify.gemspec"
  ]
  s.homepage = %q{http://github.com/gregmoreno/openamplify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Wrapper for the OpenAmplify API}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.2"])
    else
      s.add_dependency(%q<json>, ["~> 1.2"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.2"])
  end
end

